### ISSUE TITLE
Installing “js2coffee@0.15.0” failed

### ISSUE THREAD

**Issue by nathancarter** [jdcrensh/atom-js2coffee#11]
> js2coffee@0.2.7 preinstall /private/var/folders/jh/g3mhz1vd37l574zwz0krtwg00000gn/T/apm-install-dir-11566-914-14ss0je/node_modules/js2coffee/node_modules/js2coffee
> npm run-script ./cyclic.js

npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "run-script" "./cyclic.js"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1

npm ERR! missing script: ./cyclic.js
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/jh/g3mhz1vd37l574zwz0krtwg00000gn/T/apm-install-dir-11566-914-14ss0je/node_modules/js2coffee/node_modules/js2coffee/npm-debug.log
npm ERR! Darwin 14.4.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/nathan/.atom/.apm/.apmrc" "--userconfig" "/Users/nathan/.atom/.apmrc" "install" "/private/var/folders/jh/g3mhz1vd37l574zwz0krtwg00000gn/T/d-11566-914-zd1ze1/package.tgz" "--target=0.22.0" "--arch=x64"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! js2coffee@0.2.7 preinstall: `npm run-script ./cyclic.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the js2coffee@0.2.7 preinstall script 'npm run-script ./cyclic.js'.
npm ERR! This is most likely a problem with the js2coffee package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run-script ./cyclic.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls js2coffee
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/jh/g3mhz1vd37l574zwz0krtwg00000gn/T/apm-install-dir-11566-914-14ss0je/npm-debug.log

**Comment by halhenke** [comment]
Same failure with a 
`js2coffee@0.2.7 preinstall: 'npm run-script ./cyclic.js'`

which seems weird because i cant find any such references in package.json.

Some googling mentions similar issues for some people surrounding the https://github.com/js2coffee/js2coffee package

i think what was once being attempted somewhere was this:

https://github.com/bevry/base/blob/master/cyclic.js

**Comment by jdcrensh** [comment]
Duplicates #3
