### ISSUE TITLE
failes to find "npm" in path while installing

### ISSUE THREAD

**Issue by duanefields** [jdcrensh/atom-js2coffee#18]
maybe an issue for nvm users?

**Comment by DavidLGoldberg** [comment]
hi @duanefields,

Did you ever get this package working?  I get very specifically the output in issue #16 .

**Comment by duanefields** [comment]
Works if installed via command line

**Comment by DavidLGoldberg** [comment]
Ah, not for me :(

(only way I install)

**Comment by jdcrensh** [comment]
Need more info on this.
