### ISSUE TITLE
Package on Atom.io is old

### ISSUE THREAD

**Issue by nmaggioni** [jdcrensh/atom-js2coffee#20]
The [published version on Atom.io](https://atom.io/packages/js2coffee) is `v0.15.0`, which is old and broken. The current version `v0.16.2` [in the _master_ branch](https://github.com/Chandler/atom-js2coffee/blob/master/package.json#L4) contains the latest fixes and installs correctly, why isn't it published on Atom's registry?

**Comment by Chandler** [comment]
hey @nmaggioni @snowyu @jdcrensh @pahakalle don't suppose anyone wants to own this atom package, I can transfer it in the atom repo I think.

I don't use atom anymore and I'm not even setup to very changes to this lib, nor do I remember how to publish it. I'm sorry I'm so terrible

**Comment by nmaggioni** [comment]
@Chandler Heh, everyone has some sort of abandoned project :)
By my understanding the process would just take a few instants:
http://flight-manual.atom.io/hacking-atom/sections/package-word-count/#publish-your-package

**Comment by jdcrensh** [comment]
@Chandler It happens. I'd be willing to take over this project.

**Comment by swrobel** [comment]
@Chandler please hand this over to @jdcrensh!

**Comment by jdcrensh** [comment]
@Chandler Thanks for the github transfer. It looks like I didn't have an atom.io account, but I created one just now.

**Comment by jdcrensh** [comment]
Hi all, I pushed the latest version to the package repo.
