### ISSUE TITLE
Install error: "./cyclic.js"

### ISSUE THREAD

**Issue by LucasKA** [jdcrensh/atom-js2coffee#3]
I'm not sure if this is a atom-js2coffee thing or a me thing, I have the NPM package installed on my machine via npm.

> js2coffee@0.2.7 preinstall /private/var/folders/hh/fgv_7zjs1m5gbv7v9k6vhg8m0000gn/T/apm-install-dir-114618-66761-1bxoci3/node_modules/js2coffee/node_modules/js2coffee
> npm run-script ./cyclic.js

npm http GET https://registry.npmjs.org/js2coffee
npm http GET https://registry.npmjs.org/loophole
npm http 304 https://registry.npmjs.org/loophole
npm http 304 https://registry.npmjs.org/js2coffee
sh: npm: command not found
npm ERR! js2coffee@0.2.7 preinstall: `npm run-script ./cyclic.js`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the js2coffee@0.2.7 preinstall script.
npm ERR! This is most likely a problem with the js2coffee package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run-script ./cyclic.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls js2coffee
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 13.3.0
npm ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/.apmrc" "--userconfig" "/Users/Lucas/.atom/.apmrc" "install" "/Users/Lucas/.atom/.node-gyp/.atom/.apm/js2coffee/0.15.0/package.tgz" "--target=0.11.10" "--arch=x64"
npm ERR! cwd /private/var/folders/hh/fgv_7zjs1m5gbv7v9k6vhg8m0000gn/T/apm-install-dir-114618-66761-1bxoci3
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.4
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /private/var/folders/hh/fgv_7zjs1m5gbv7v9k6vhg8m0000gn/T/apm-install-dir-114618-66761-1bxoci3/npm-debug.log
npm ERR! not ok code 0

**Comment by LucasKA** [comment]
Hey y'all, I was tired of going to the js2coffee site to do my conversion, so I whipped up a package using the more modern Atom API and the new js2coffee package.

Super early and not a lot of error handling, but simple and effective, would love some feedback and help on some simple features.

https://github.com/LucasKA/coffee-porter

**Comment by jdcrensh** [comment]
Fixed by #17
