### ISSUE TITLE
Error activating package config for “js2coffee” TypeError: evalmachine

### ISSUE THREAD

**Issue by noctivityinc** [jdcrensh/atom-js2coffee#6]
Error activating package config for “js2coffee” TypeError: evalmachine.<anonymous>:1
const END = 0, NEWLINE = 1, SEMICOLON = 2, COMMA = 3, ASSIGN = 4, HOOK = 5, CO
^
Identifier 'END' has already been declared {stack: (...), message: "evalmachine.<anonymous>:1↵const END = 0, NEWLINE =…, CO↵^↵Identifier 'END' has already been declared"}

**Comment by jdcrensh** [comment]
Duplicates #4
