### ISSUE TITLE
FYI: js2coffee v2.0.0 release due soon

### ISSUE THREAD

**Issue by rstacruz** [jdcrensh/atom-js2coffee#7]
https://github.com/js2coffee/js2coffee/issues/333

command-line API will remain unchanged, but the JavaScript API (specifically, the result of `js2coffee.build()`) will change.

https://github.com/js2coffee/js2coffee#programatic-api

**Comment by rstacruz** [comment]
and its now out!

https://github.com/js2coffee/js2coffee/blob/master/notes/Migration_guide.md

**Comment by LucasKA** [comment]
I wrote an Atom package with the new js2coffee API, well sorta, it's not doing anything all that complex.

https://github.com/LucasKA/coffee-porter
